name: lcrm-target-customer
version: 1.0.0
description: 基于9大战场框架+实时搜索验证，快速判断客户匹配度、准备拜访资料、规划行业拓展。

triggers:
  - 客户匹配
  - 匹配度
  - 目标客群
  - 客群策略
  - 这个客户值得打吗
  - 值得拜访吗
  - 行业拓展
  - 哪些客户
  - 客户画像
  - 目标客户
  - 是不是我的客户
  - 帮我研究一下

instructions: |
  当用户需要判断客户匹配度、做拜访前调研或规划行业拓展时，执行以下步骤：

  ## 前置：加载知识库

  加载产品体系文档：`当前知识库（按需增加和更新）/claude.md`
  加载目标客户名单：`当前知识库（按需增加和更新）/数字员工（主打的售前数字员工产品）/典型画像的客户名单20260224.csv`

  ## 场景判断

  根据用户输入判断场景：
  - 提供公司名 → 场景A（快速匹配度判断）或场景B（深度调研）
  - 提供行业名 → 场景C（行业拓展规划）
  - 不确定时先问："你是要判断某个具体客户，还是规划某个行业的拓展？"

  ## 场景A：快速判断客户匹配度

  Step 1: 搜索验证基础信息
  使用 mcp__grok-search__web_search 搜索："客户名 主营业务 主要产品 2024"

  Step 2: 匹配9大战场
  - 对照战场特征，判断所属战场
  - 逐一验证5大核心能力（①②③④⑤），每项给出"有/无/待验证"
  - 禁止用行业标签跳过验证（如"央企=关系销售"、"制造业=无标书"）
  - ④标书场景：只要客户有招投标业务，无论销售模式，均视为有场景

  Step 3: 输出匹配度分析（表格格式）
  - 所属战场
  - 匹配能力（①②③④⑤中的哪几个）
  - 匹配度（⭐1-5星 + 高/中/低）
  - 判断依据（3个关键点，标注✅已验证/⚠️待验证/❓推测）
  - 建议（打/暂缓/不打，理由一句话）

  ## 场景B：拜访前深度调研

  Step 1: 搜索公司基础信息："客户名 公司简介 主营业务 规模"
  Step 2: 搜索最新动态："客户名 2024 2025 财报 战略 数字化"
  Step 3: 搜索产品与场景："客户名 产品 解决方案 SKU 选型"
  Step 4: 基于搜索结果 + 战场特征，分析痛点，生成拜访策略

  输出内容：
  - 公司最新动态（✅已验证）
  - 主营业务与产品（✅已验证）
  - 业务痛点（对应哪个战场特征）
  - 价值主张（针对性匹配5大能力）
  - 沟通切入点（第一句话怎么说）

  ## 场景C：行业拓展规划

  Step 1: 搜索行业格局："行业名 头部企业 市场格局 2024 2025"
  Step 2: 对照9大战场，确认所属战场和子战场
  Step 3: 输出优先级排序

  输出内容：
  - 行业格局（✅已验证）
  - 推荐目标客户清单（带匹配度）
  - 优先级排序依据
  - 首轮触达建议

  ## 9大战场速查

  | 战场 | 子战场 | 核心匹配能力 |
  |------|--------|------------|
  | 泛工业自动化 | 工控与驱动、机器人、智能制造、智能物流 | ①③ |
  | 智慧楼宇与安防 | 安防、商显、暖通 | ②④ |
  | ICT与算力设施 | 网络、光通信 | ③④ |
  | 电力与新能源 | 输配电、光伏储能 | ①④⑤ |
  | 电子元器件 | 主动IC、被动元件 | ①③ |
  | 机械重工与车辆 | 工程机械、商用车 | ②⑤ |
  | 过程工业与流体 | 仪表传感、流体控制 | ②③ |
  | 医疗与生命科学 | 医疗器械 | ①④ |
  | 企业软件与服务 | 管理软件 | ②⑤ |

  5大核心能力：①深度知识摄入 ②咨询式需求引导 ③确定性逻辑推理 ④强合规与标书生成 ⑤方案与报价闭环

  ## 信息可靠性规则

  - 所有客户信息必须搜索验证后输出
  - 输出时标注：✅已验证 / ⚠️待验证 / ❓推测
  - 搜索结果与知识库冲突时，以搜索结果为准
