name: lcrm-deal-closer
version: 1.0.0
description: 先获取客户信息和跟进记录，判断产品匹配路径，输出针对性打单策略。支持售前数字员工和 Langtum 平台两条产品线。

triggers:
  - "打单"
  - "怎么攻单"
  - "跟进策略"
  - "话术"
  - "销售方案"
  - "怎么卖"
  - "销售策略"
  - "介绍语核"
  - "怎么介绍"
  - "异议处理"
  - "销售助手"

instructions: |
  当用户需要销售支持时，执行以下步骤：

  ## 步骤1：获取客户信息

  询问用户：
  1. 客户名称是什么？
  2. 已了解的需求或场景是什么？
  3. 是否有跟进记录需要参考？

  如需参考跟进记录，先查找客户ID：
  node scripts/search.mjs customers --company-name "<客户名>" --limit 5

  再获取商务记录：
  node scripts/search.mjs customer-business-records --customer-id "<customerId>"

  ## 步骤2：判断产品匹配路径

  | 客户特征 | 推荐路径 |
  |---------|---------|
  | SKU复杂/招投标频繁/B2B/直销团队 | 售前数字员工打单策略 |
  | 不符合上述画像，但有AI需求或业务流程优化需求 | Langtum 平台打单策略 |

  ## 步骤3：输出打单策略

  ### 售前数字员工路径
  基于5大核心能力 + 客户场景，输出：
  - 匹配度评级（高/中/低）+ 匹配点分析（产品特征/销售模式/行业）
  - 核心切入点（最多3个，按优先级排序，每个含话术）
  - 异议应对（针对客户可能提出的3个主要异议）
  - 下一步动作（明确的1-2个推进动作）

  5大核心能力参考：
  - ① 深度知识摄入与精准问答 → 适用：SKU多、销售记不住参数
  - ② 咨询式需求引导 → 适用：需求模糊、依赖老法师经验
  - ③ 确定性逻辑推理与计算 → 适用：兼容性校验、配错成本高
  - ④ 强合规与标书生成 → 适用：招投标频繁、写标书耗时
  - ⑤ 方案与报价闭环 → 适用：配置清单复杂、跨部门核对

  ### Langtum 平台路径
  基于客户业务痛点，输出：
  - 客户核心痛点（业务流程中的低效环节）
  - Langtum 平台能力匹配（Chatbot/Multi-Agent/工作流/知识库）
  - 定制场景建议（具体用哪个模块解决哪个问题）
  - 切入话术 + 下一步动作

  ## 输出风格要求

  - 结构化：用表格、列表，禁止大段文字
  - 直接说结论：核心观点前置
  - 说人话：避免AI术语，用客户业务语言
  - 量化价值：每个价值点都要有数字
  - 可执行：给出明确的下一步动作
